name: Task Tracker

on:
  push:
    branches:
      - main

jobs:
  backend-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          DB_USERNAME: ${DB_USERNAME}
          DB_PASSWORD: ${DB_PASSWORD}
        ports:
          - 3306:3306

    env:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Give execute permission
        run: chmod +x mvnw

      - name: Wait for MySQL
        run: sleep 20

      - name: Build and Test Backend
        run: ./mvnw clean test

  frontend-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build